version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - sites:/etc/nginx/conf.d
      - certs:/etc/letsencrypt
      - certbot_static:/var/www/certbot
    networks:
      - intranet
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot_static:/var/www/certbot
    networks:
      - intranet
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

volumes:
  sites:
    name: nginx-sites
  certs:
    name: certbot-conf
  certbot_static:

networks:
  intranet:
    name: nginx-certbot-network